config/routes.rb
Photoload::Application.routes.draw do
  resources :photos

  root :to => 'users#index'
  get "sessions/new"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'myaccount/:id', to: 'users#show', as: 'myaccount'
  get 'new_upload', to: 'photos#new', as: "new_upload"
  get 'photo/:id', to: 'photos#show', as: 'viewphoto'
  resources :users
  resources :sessions
  resources :tags
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :presence => true
  belongs_to :users
  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :photos

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :presence => true
  has_many :photos
  has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  belongs_to :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authorize, only: [:new, :update]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(photo_params)
    if @photo.save
      redirect_to root_url, notice: "Photo added"
    else
      render "new"
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @user = User.find(@photo.user_id)
    @tags = Tag.all
    @tag = Tag.new

  end

  private
  def photo_params
   params.require(:photo).permit(:image, :user_id, :caption)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end



  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    params[:tag][:user_id].each do |user_id|
      if user_id != ''
        @tag = Tag.create(:user_id => user_id)
      end
    end
    if @tag.save
      redirect_to root_url, notice: "User has been tagged"
    else
      redirect_to root_url
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.all
    @photos = Photo.all
    @tags = Tag.all
  end

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thanks for signing up"
    else
      redirect_to signup_path
    end
  end

  def delete
    current_user.destroy
  end


  private
  def user_params
    params.require(:user).permit(:name, :password, :user_id, :password_confirmation, :photo_id, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoload</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= bootstrap_flash %>
  <div class="container">
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">

      <div class="navbar-form navbar-right">
       <% if current_user %>
      Logged in as <%= current_user.name %>
      |
      <%= link_to "Home", root_path %>
      |
      <%= link_to "Upload Photo", new_upload_path %>
      |
      <%= link_to "My Account", myaccount_path(current_user) %>
      |
      <%= link_to "Log Out", logout_path %>
      <% else %>
      <%= link_to "Sign Up", signup_path %> or <%= link_to "Log In", login_path %>
      <% end %>
  </div>
  </nav>
  </div>
</div>
</div>
<br><br>

<%= yield %>
</div>


</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
<div class="form-group">
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  <%= f.file_field :image %>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
</div>
<%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/photos/new.html.erb
<h1>Add a new photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<h1>Hello</h1>


<%= image_tag Photo.find_by_id(params[:id]).image %>
<br>
<h2><%= Photo.find_by_id(params[:id]).caption %></h2>

<h3>Posted by: <%= @user.name %>

<h4>Tag a user</h4>
<h4>Tagged users</h4>


<%= form_for @tag do |f| %>
  <%= f.collection_check_boxes :user_id, User.all, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label "User Name" %>
    <%= f.text_field :name %><br>
    <%= f.label "Avatar" %>
    <%= f.file_field :avatar %>
    <%= f.label "Password" %>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/users/index.html.erb
<h1>PhotoLoad</h1>
<% if Photo.all != nil %>
<% Photo.all.each do |image| %>
  <%= link_to image_tag(image.image(:thumb)), photo_path(image.id)  %>
  <br>
  <%= image.caption %>, posted by: <%= User.find(image.user_id).name %>
  <br>
  <% end %>
<% else %>
<p>No photos availible</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= image_tag @user.avatar(:thumb) %>
<br><br>
<h1>Photos uploaded by <%= @user.name %></h1>
  <% if Photo.find_by_user_id(session[:user_id]) != nil %>
  <%= image_tag Photo.find_by_user_id(session[:user_id]).image(:medium) %>
  <% else %>
  <p>No photos uploaded</p>
  <% end %>